export const AUDIT_EVENTS = {
  AUTH_SIGNUP_SUCCESS: "auth.signup.success",
  AUTH_LOGIN_SUCCESS: "auth.login.success",
  AUTH_LOGIN_FAILED: "auth.login.failed",
  AUTH_LOGOUT: "auth.logout",
  AUTH_REFRESH_SUCCESS: "auth.refresh.success",
  AUTH_REFRESH_FAILED: "auth.refresh.failed",
  AUTH_EMAIL_VERIFIED: "auth.email.verified",
  AUTH_VERIFICATION_RESEND: "auth.email.verification_resent",
  AUTH_FORGOT_PASSWORD_REQUESTED: "auth.password.forgot_requested",
  AUTH_PASSWORD_RESET_SUCCESS: "auth.password.reset.success",
  AUTH_SESSION_REVOKED: "auth.session.revoked",
  AUTH_SESSIONS_VIEWED: "auth.session.list_viewed",
  USER_PROFILE_VIEWED: "user.profile.viewed",
  USER_PROFILE_UPDATED: "user.profile.updated",
  USER_PROFILE_DELETED: "user.profile.deleted",
  ORG_CREATED: "organization.created",
  ORG_LISTED: "organization.listed",
  ORG_VIEWED: "organization.viewed",
  ORG_UPDATED: "organization.updated",
  ORG_DELETED: "organization.deleted",
  ORG_INVITE_SENT: "organization.invite.sent",
  ORG_INVITE_VIEWED: "organization.invite.viewed",
  ORG_INVITES_VIEWED: "organization.invite.listed",
  ORG_INVITE_ACCEPTED: "organization.invite.accepted",
  ORG_INVITE_REVOKED: "organization.invite.revoked",
  ORG_MEMBER_ROLE_UPDATED: "organization.member.role_updated",
  ORG_OWNERSHIP_TRANSFERRED: "organization.ownership.transferred",
  OAUTH_START: "oauth.start",
  OAUTH_CALLBACK_SUCCESS: "oauth.callback.success",
  OAUTH_CALLBACK_FAILED: "oauth.callback.failed",
};

export const AUDIT_CATEGORY = {
  AUTH: "auth",
  USER: "user",
  ORGANIZATION: "organization",
  OAUTH: "oauth",
  SYSTEM: "system",
};

export const AUDIT_STATUS = {
  SUCCESS: "success",
  FAILURE: "failure",
};
